In [2]:
import numpy as np

In [3]:
# 1D Array
arr1 = np.array([10, 20, 30, 40, 50])
print("1D Array:", arr1)

# 2D Array
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])
print("2D Array:\n", arr2)

# 3D Array
arr3 = np.array([[[1, 2], [3, 4]],
                 [[5, 6], [7, 8]]])
print("3D Array:\n", arr3)

1D Array: [10 20 30 40 50]
2D Array:
 [[1 2 3]
 [4 5 6]]
3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [4]:
arr = np.array([[10, 20, 30],
                [40, 50, 60]])

print("Dimensions:", arr.ndim)
print("Shape:", arr.shape)
print("Data Type:", arr.dtype)

Dimensions: 2
Shape: (2, 3)
Data Type: int64


In [5]:
arr = np.array([10, 20, 30, 40, 50])

print("First element:", arr[0])
print("Third element:", arr[2])
print("Last element:", arr[-1])

First element: 10
Third element: 30
Last element: 50


In [8]:
arr = np.array([[10, 20, 30],[40, 50, 60]])
print(arr[0, 1])
print(arr[1, 2])

20
60


In [9]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[1:4])
print(arr[:3])
print(arr[2:])

[20 30 40]
[10 20 30]
[30 40 50]


In [15]:
arr = np.array([1, 2, 3, 4, 5, 6])

new_arr = arr.reshape(2, 3)
print(new_arr)

[[1 2 3]
 [4 5 6]]


In [16]:
# Zeros
print(np.zeros(5))

# Ones
print(np.ones(5))

# arange
print(np.arange(1, 10))

# linspace
print(np.linspace(0, 10, 5))

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[1 2 3 4 5 6 7 8 9]
[ 0.   2.5  5.   7.5 10. ]


In [19]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3 ])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: [11 22 33]
Subtraction: [ 9 18 27]
Multiplication: [10 40 90]
Division: [10. 10. 10.]


In [20]:
arr = np.array([1, 2, 3, 4, 5])

print(arr * 2)
print(arr + 10)
print(arr ** 2)

[ 2  4  6  8 10]
[11 12 13 14 15]
[ 1  4  9 16 25]


In [21]:
arr = np.array([10, 25, 30, 45, 50])

# Find values greater than 30
print(arr[arr > 30])

# Find values less than 40
print(arr[arr < 40])

[45 50]
[10 25 30]


In [22]:
arr = np.array([10, 20, 30, 40, 50])

print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Minimum:", np.min(arr))
print("Maximum:", np.max(arr))
print("Median:", np.median(arr))

Sum: 150
Mean: 30.0
Minimum: 10
Maximum: 50
Median: 30.0
